# Form implementation generated from reading ui file './UI_Form/login_page.ui'
#
# Created by: PyQt6 UI code generator 6.0.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_login_widget(object):
    def setupUi(self, login_widget):
        login_widget.setObjectName("login_widget")
        login_widget.setEnabled(True)
        login_widget.resize(700, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(login_widget.sizePolicy().hasHeightForWidth())
        login_widget.setSizePolicy(sizePolicy)
        login_widget.setMinimumSize(QtCore.QSize(700, 500))
        login_widget.setMaximumSize(QtCore.QSize(650, 450))
        login_widget.setAcceptDrops(False)
        login_widget.setStyleSheet("QWidget {\n"
"    background-image: url(:/login/login_background.png);\n"
"    background-repeat: no-repeat;\n"
"    backgrond-position: center;\n"
"}\n"
"\n"
"QFrame {\n"
"    background: none;\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"    alignment: center;\n"
"    padding-right: 10px;\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"QLabel {\n"
"    background: none;\n"
"    color: #0c7b93;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background: none;\n"
"    background-color: white;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color: #0c7b93;\n"
"    border-top: none;\n"
"    border-left: none;\n"
"    border-right: none;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(login_widget)
        self.verticalLayout.setContentsMargins(10, 0, 10, 60)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 61)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(login_widget)
        self.label.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    background: none;\n"
"    padding-left: 10px;\n"
"    color: white;\n"
"}")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignLeft)
        self.pushButton_2 = QtWidgets.QPushButton(login_widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background: none;\n"
"    border: none;\n"
"    color: rgb(17, 135, 157);\n"
"    text-align: right;\n"
"    padding-right: 50px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(183, 182, 184);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.login_frame = QtWidgets.QFrame(login_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_frame.sizePolicy().hasHeightForWidth())
        self.login_frame.setSizePolicy(sizePolicy)
        self.login_frame.setMinimumSize(QtCore.QSize(350, 250))
        self.login_frame.setMaximumSize(QtCore.QSize(350, 250))
        self.login_frame.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.login_frame.setStyleSheet("")
        self.login_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.login_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.login_frame.setObjectName("login_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.login_frame)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.login_label = QtWidgets.QLabel(self.login_frame)
        self.login_label.setMaximumSize(QtCore.QSize(120, 35))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.login_label.setFont(font)
        self.login_label.setStyleSheet("QLabel {\n"
"    padding: 0px;\n"
"}")
        self.login_label.setScaledContents(False)
        self.login_label.setAlignment(QtCore.Qt.Alignment.AlignLeading|QtCore.Qt.Alignment.AlignLeft|QtCore.Qt.Alignment.AlignVCenter)
        self.login_label.setObjectName("login_label")
        self.verticalLayout_3.addWidget(self.login_label)
        self.username_field = QtWidgets.QLineEdit(self.login_frame)
        self.username_field.setMinimumSize(QtCore.QSize(300, 40))
        self.username_field.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(True)
        self.username_field.setFont(font)
        self.username_field.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.username_field.setStyleSheet("")
        self.username_field.setText("")
        self.username_field.setAlignment(QtCore.Qt.Alignment.AlignLeading|QtCore.Qt.Alignment.AlignLeft|QtCore.Qt.Alignment.AlignVCenter)
        self.username_field.setClearButtonEnabled(False)
        self.username_field.setObjectName("username_field")
        self.verticalLayout_3.addWidget(self.username_field)
        self.password_field = QtWidgets.QLineEdit(self.login_frame)
        self.password_field.setMinimumSize(QtCore.QSize(300, 40))
        self.password_field.setMaximumSize(QtCore.QSize(300, 40))
        self.password_field.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.password_field.setStyleSheet("")
        self.password_field.setText("")
        self.password_field.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_field.setObjectName("password_field")
        self.verticalLayout_3.addWidget(self.password_field)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.login_frame)
        self.pushButton.setMinimumSize(QtCore.QSize(150, 40))
        self.pushButton.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background: none;\n"
"    border: none;\n"
"    color: rgb(50, 50, 50);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(17, 135, 157);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.signin_button = QtWidgets.QPushButton(self.login_frame)
        self.signin_button.setMinimumSize(QtCore.QSize(100, 40))
        self.signin_button.setMaximumSize(QtCore.QSize(100, 40))
        self.signin_button.setStyleSheet("QPushButton {\n"
"    background: none;\n"
"    background-color: #0c7b93;\n"
"    border-radius: 10px;\n"
"    font: bold;\n"
"    font-size: 18px;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: none;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #0C5A76, stop: 1 #0c7b93);\n"
"}")
        self.signin_button.setObjectName("signin_button")
        self.horizontalLayout.addWidget(self.signin_button)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.setStretch(2, 1)
        self.verticalLayout.addWidget(self.login_frame, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout.setStretch(1, 2)

        self.retranslateUi(login_widget)
        QtCore.QMetaObject.connectSlotsByName(login_widget)

    def retranslateUi(self, login_widget):
        _translate = QtCore.QCoreApplication.translate
        login_widget.setWindowTitle(_translate("login_widget", "CarRental"))
        self.label.setText(_translate("login_widget", "<html><head/><body><p><span style=\" color:#adafb4;\">Car</span><span style=\" color:#dadee2;\">Rental</span></p></body></html>"))
        self.pushButton_2.setText(_translate("login_widget", "Create Account"))
        self.login_label.setText(_translate("login_widget", "<strong>Login</strong>"))
        self.username_field.setPlaceholderText(_translate("login_widget", "Username"))
        self.password_field.setPlaceholderText(_translate("login_widget", "Password"))
        self.pushButton.setText(_translate("login_widget", "Forgot Password"))
        self.signin_button.setText(_translate("login_widget", "Sign In"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_widget = QtWidgets.QWidget()
    ui = Ui_login_widget()
    ui.setupUi(login_widget)
    login_widget.show()
    sys.exit(app.exec())
